# Generated by Django 4.0.3 on 2022-03-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
