# Generated by Django 4.0.3 on 2022-03-22 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoops', '0002_alter_league_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='phone_number',
        ),
    ]
