# Generated by Django 4.0.3 on 2022-03-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoops', '0003_remove_player_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='played_on',
            field=models.DateTimeField(),
        ),
    ]
