# Generated by Django 4.0.3 on 2022-03-26 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoops', '0004_alter_match_played_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='games_played',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='wins',
        ),
        migrations.AddField(
            model_name='playerstats',
            name='match',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='match', to='hoops.match'),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='result',
            field=models.CharField(choices=[('W', 'Won'), ('L', 'Lost'), ('I', 'In Progress')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league', to='hoops.league'),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='hoops.player'),
        ),
    ]
