# Generated by Django 4.0.3 on 2022-03-26 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoops', '0005_alter_match_options_alter_player_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstats',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='hoops.match'),
        ),
    ]
