# Generated by Django 4.0.3 on 2022-03-29 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoops', '0006_alter_playerstats_match'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerstats',
            options={'verbose_name_plural': 'Player Stats'},
        ),
        migrations.AddField(
            model_name='playerstats',
            name='played_as',
            field=models.CharField(choices=[('H', 'Host'), ('G', 'Guest')], default='U', max_length=1),
        ),
    ]
