# Generated by Django 4.0.3 on 2022-03-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoops', '0007_alter_playerstats_options_playerstats_played_as'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='l_streak',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerstats',
            name='w_streak',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
