# Generated by Django 4.0.3 on 2022-03-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoops', '0008_playerstats_l_streak_playerstats_w_streak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstats',
            name='l_streak',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='w_streak',
            field=models.IntegerField(),
        ),
    ]
