# Generated by Django 4.0.3 on 2022-04-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoops', '0009_alter_playerstats_l_streak_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstats',
            name='l_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='w_streak',
            field=models.IntegerField(default=0),
        ),
    ]
